// Reads .env and bakes the values into config.generated.js — a plain JS
// module the extension can actually load. Chrome extensions run in the
// browser with no filesystem access, so there's no way to read .env at
// runtime; this is the closest honest equivalent, run once at build time
// whenever .env changes.
//
// Usage: npm run build:config

const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });

const PLATFORM_BASE_URL = process.env.PLATFORM_BASE_URL || 'http://localhost:9001';
const INTELLIGENCE_WS_URL = process.env.INTELLIGENCE_WS_URL || 'ws://localhost:8000/ws';
const DASHBOARD_URL = process.env.DASHBOARD_URL || 'http://localhost:3000/dashboard/billing';

const output = `// GENERATED by build-config.js from .env — do not edit directly.
// Run \`npm run build:config\` after changing .env to regenerate this file.
export const PLATFORM_BASE_URL = ${JSON.stringify(PLATFORM_BASE_URL)};
export const INTELLIGENCE_WS_URL = ${JSON.stringify(INTELLIGENCE_WS_URL)};
export const DASHBOARD_URL = ${JSON.stringify(DASHBOARD_URL)};
`;

fs.writeFileSync(path.join(__dirname, 'config.generated.js'), output);
console.log('Wrote config.generated.js from .env:');
console.log('  PLATFORM_BASE_URL   =', PLATFORM_BASE_URL);
console.log('  INTELLIGENCE_WS_URL =', INTELLIGENCE_WS_URL);
console.log('  DASHBOARD_URL       =', DASHBOARD_URL);
